////////////////////////////////////////////////////////////////
//
//  Name: Integration test executor
//  GitHub repository: https://github.com/2ndSightLab/rust-common-tests.git
//  File: tests/integration_rust_common_tests.rs
//  Copyright: © 2025 2nd Sight Lab, LLC
//
//  Executes all integration tests
//
//  This software, which includes components generated with the assistance of artificial
//  intelligence, is free for personal, educational, and non-profit use, provided that
//  the included copyright notice is retained in all copies or substantial portions of
//  the software. This license, however, does not grant permission for any commercial
//  use, which requires obtaining a separate commercial license from the author. The
//  software is provided "as is," without any warranty, and the author cannot be held
//  liable for any damages or claims arising from its use. By using this software,
//  all users acknowledge that any potentially uncopyrightable portions generated by
//  AI are governed by the terms of this license as part of the overall work.
//
////////////////////////////////////////////////////////////////

mod integration_rust_common_tests {
    pub mod common {
        pub mod test_graceful_shutdown_handling;
        pub mod test_prerequisites;
        pub mod test_security_workflow_integration;
        pub mod test_system_resource_monitoring;
    }
}
