////////////////////////////////////////////////////////////////
//
//  Name: Unit test executor
//  GitHub repository: https://github.com/2ndSightLab/rust-common-tests.git
//  File: tests/unit_test_rust_common_tests.rs
//  Copyright: © 2025 2nd Sight Lab, LLC
//
//  Executes all unit tests that validate standards and best practices
//
//  This software, which includes components generated with the assistance of artificial
//  intelligence, is free for personal, educational, and non-profit use, provided that
//  the included copyright notice is retained in all copies or substantial portions of
//  the software. This license, however, does not grant permission for any commercial
//  use, which requires obtaining a separate commercial license from the author. The
//  software is provided "as is," without any warranty, and the author cannot be held
//  liable for any damages or claims arising from its use. By using this software,
//  all users acknowledge that any potentially uncopyrightable portions generated by
//  AI are governed by the terms of this license as part of the overall work.
//
////////////////////////////////////////////////////////////////

mod unit_tests_rust_common_tests {
    pub mod common {
        pub mod test_best_practices_compliance;
        pub mod test_cargo_allows_screaming_snake_case;
        pub mod test_common_tests_display;
        pub mod test_local_tests_display;
        pub mod test_module_naming;
        pub mod test_no_magic_numbers;
        pub mod test_non_snake_case_override_present;
        pub mod test_screaming_snake_case_config;
        pub mod test_screaming_snake_case_variables;
        pub mod test_script_validation;
        pub mod test_service_config_validation;
    }
}
