////////////////////////////////////////////////////////////////
//
//  Name: Prerequisites check integration test
//  GitHub repository: https://github.com/2ndSightLab/rust-common-tests.git
//  File: tests/integration_rust_common_tests/common/test_prerequisites.rs
//  Copyright: © 2025 2nd Sight Lab, LLC
//
//  Validates that required dependencies and setup are present
//
//  This software, which includes components generated with the assistance of artificial
//  intelligence, is free for personal, educational, and non-profit use, provided that
//  the included copyright notice is retained in all copies or substantial portions of
//  the software. This license, however, does not grant permission for any commercial
//  use, which requires obtaining a separate commercial license from the author. The
//  software is provided "as is," without any warranty, and the author cannot be held
//  liable for any damages or claims arising from its use. By using this software,
//  all users acknowledge that any potentially uncopyrightable portions generated by
//  AI are governed by the terms of this license as part of the overall work.
//
////////////////////////////////////////////////////////////////

/// Check test prerequisites
/// # Errors
/// Returns error if basic project structure is missing
pub fn check_test_prerequisites() -> Result<(), String> {
    let CURRENT_DIR =
        std::env::current_dir().map_err(|e| format!("Failed to get current directory: {e}"))?;

    // Skip if we're in the common tests directory itself
    if CURRENT_DIR.file_name().unwrap_or_default() == "rust-common-tests" {
        return Ok(());
    }

    // Check for basic project structure
    let SRC_DIR = CURRENT_DIR.join("src");
    if !SRC_DIR.exists() {
        return Err("src directory not found".to_string());
    }

    let CARGO_PATH = CURRENT_DIR.join("Cargo.toml");
    if !CARGO_PATH.exists() {
        return Err("Cargo.toml not found".to_string());
    }

    Ok(())
}

/// Check if service config exists
/// # Panics
/// Panics if current directory cannot be determined
#[must_use]
#[allow(dead_code)]
pub fn has_service_config() -> bool {
    let CURRENT_DIR = std::env::current_dir().expect("Failed to get current directory");
    let SERVICE_CONFIG_PATH = CURRENT_DIR.join("service.toml");
    SERVICE_CONFIG_PATH.exists()
}

#[test]
fn test_prerequisites_check() {
    match check_test_prerequisites() {
        Ok(()) => println!("Prerequisites check passed"),
        Err(e) => println!("Prerequisites check failed: {e}"),
    }
}
