////////////////////////////////////////////////////////////////
//
//  Name: Security checks module declarations
//  GitHub repository: https://github.com/2ndSightLab/rust-common-tests.git
//  File: tests/security_checks_rust_common_tests/common/mod.rs
//  Copyright: © 2025 2nd Sight Lab, LLC
//
//  Module declarations for security validation tests
//
//  This software, which includes components generated with the assistance of artificial
//  intelligence, is free for personal, educational, and non-profit use, provided that
//  the included copyright notice is retained in all copies or substantial portions of
//  the software. This license, however, does not grant permission for any commercial
//  use, which requires obtaining a separate commercial license from the author. The
//  software is provided "as is," without any warranty, and the author cannot be held
//  liable for any damages or claims arising from its use. By using this software,
//  all users acknowledge that any potentially uncopyrightable portions generated by
//  AI are governed by the terms of this license as part of the overall work.
//
////////////////////////////////////////////////////////////////

pub mod test_code_separation;
pub mod test_dependency_audit;
pub mod test_dependency_validation;
pub mod test_file_permissions;
pub mod test_hardcoded_secrets;
pub mod test_process_exit;
