////////////////////////////////////////////////////////////////
//
//  Name: Dependency validation security test
//  GitHub repository: https://github.com/2ndSightLab/rust-common-tests.git
//  File: tests/security_checks_rust_common_tests/common/test_dependency_validation.rs
//  Copyright: © 2025 2nd Sight Lab, LLC
//
//  Validates that essential dependencies are properly declared in Cargo.toml
//
//  This software, which includes components generated with the assistance of artificial
//  intelligence, is free for personal, educational, and non-profit use, provided that
//  the included copyright notice is retained in all copies or substantial portions of
//  the software. This license, however, does not grant permission for any commercial
//  use, which requires obtaining a separate commercial license from the author. The
//  software is provided "as is," without any warranty, and the author cannot be held
//  liable for any damages or claims arising from its use. By using this software,
//  all users acknowledge that any potentially uncopyrightable portions generated by
//  AI are governed by the terms of this license as part of the overall work.
//
////////////////////////////////////////////////////////////////

#[cfg(test)]
mod test_dependency_validation_tests {
    use std::fs;
    use std::path::Path;

    #[test]
    fn test_all_dependencies_declared() {
        let CARGO_PATH = Path::new("Cargo.toml");
        assert!(CARGO_PATH.exists(), "Cargo.toml not found");

        let CARGO_CONTENT = fs::read_to_string(CARGO_PATH).unwrap();

        // Check that essential dependencies are declared
        assert!(CARGO_CONTENT.contains("libc ="), "Missing libc dependency");
        assert!(
            CARGO_CONTENT.contains("thiserror ="),
            "Missing thiserror dependency"
        );
        assert!(CARGO_CONTENT.contains("log ="), "Missing log dependency");
        assert!(
            CARGO_CONTENT.contains("serde ="),
            "Missing serde dependency"
        );
    }
}
